kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: observability
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 3000
        hostPort: 3000
      - containerPort: 4317
        hostPort: 4317
      - containerPort: 4318
        hostPort: 4318
